### ISSUE TITLE
Running the example

### ISSUE THREAD

**Issue by hubyhuby** [vlang/mongo#5]
I am newbe to V, trying to run the exemple I get the following :
" error: cannot use `&string` as `&char` in argument 2 to `C.bson_oid_to_string` "

![image](https://user-images.githubusercontent.com/26340942/123826826-66089d00-d900-11eb-9482-b59f0581f585.png)

**Comment by hubyhuby** [comment]
Tried with the one line patch #6  : 
![image](https://user-images.githubusercontent.com/26340942/124376307-b2f4c680-dca6-11eb-8f8a-b1738ede6c00.png)

**Comment by hubyhuby** [comment]
Almost there ;) It works until I need "BSON"
![image](https://user-images.githubusercontent.com/26340942/129590959-ccb36e5e-65c3-4efd-9df4-f7a54a7c1287.png)
I have the libs on my ubuntu mate 20.04
![image](https://user-images.githubusercontent.com/26340942/129591012-69d70c94-9ac4-4745-9874-c6d6a7c56833.png)
![image](https://user-images.githubusercontent.com/26340942/129591051-ba673c39-e66f-4800-9d79-7c994885c723.png)

![image](https://user-images.githubusercontent.com/26340942/129591507-48abe58c-a30d-4d74-aefc-320d33e188a9.png)

**Comment by Omarabdul3ziz** [comment]
Did you find any solution for this?

**Comment by enghitalo** [comment]
You ca try new version `v up && v install mongo`

**Comment by enghitalo** [comment]
> Did you find any solution for this?

You ca try new version `v up && v install mongo`

**Comment by hubyhuby** [comment]
Now the example seems to work on my side with ubuntu 22.04 packages  and updating V command as you suggested
![image](https://user-images.githubusercontent.com/26340942/193446700-f63ec1df-55b1-4bf7-8843-ea91440d9ad4.png)
